-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.23 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for weblog
CREATE DATABASE IF NOT EXISTS `weblog` /*!40100 DEFAULT CHARACTER SET latin5 */;
USE `weblog`;

-- Dumping structure for table weblog.iletisim
CREATE TABLE IF NOT EXISTS `iletisim` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `eposta` varchar(100) NOT NULL,
  `konu` varchar(150) NOT NULL,
  `mesaj` varchar(600) NOT NULL,
  `tarihSaat` datetime NOT NULL,
  `ip` char(50) NOT NULL,
  `goruldu` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin5;

-- Dumping data for table weblog.iletisim: 4 rows
/*!40000 ALTER TABLE `iletisim` DISABLE KEYS */;
/*!40000 ALTER TABLE `iletisim` ENABLE KEYS */;

-- Dumping structure for table weblog.kategoriler
CREATE TABLE IF NOT EXISTS `kategoriler` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `adi` varchar(70) NOT NULL,
  `sira` int(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin5;

-- Dumping data for table weblog.kategoriler: 7 rows
/*!40000 ALTER TABLE `kategoriler` DISABLE KEYS */;
INSERT INTO `kategoriler` (`id`, `adi`, `sira`) VALUES
	(1, 'Asp.net', 100),
	(2, 'c#', 200),
	(3, 'Html', 300),
	(4, 'Bootstrap', 400),
	(5, 'Css', 500),
	(6, 'Php', 600),
	(7, 'Photoshop', 700);
/*!40000 ALTER TABLE `kategoriler` ENABLE KEYS */;

-- Dumping structure for table weblog.yazarlar
CREATE TABLE IF NOT EXISTS `yazarlar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `adi` varchar(50) NOT NULL,
  `soyadi` varchar(50) NOT NULL,
  `cinsiyet` char(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=latin5;

-- Dumping data for table weblog.yazarlar: 20 rows
/*!40000 ALTER TABLE `yazarlar` DISABLE KEYS */;
INSERT INTO `yazarlar` (`id`, `adi`, `soyadi`, `cinsiyet`) VALUES
	(1, 'Tolay', 'Akgül', 'E'),
	(2, 'Sezan', 'Akgeyik', 'E'),
	(3, 'Zehra', 'Dönmez', 'E'),
	(4, 'Saru', 'Mut', 'K'),
	(5, 'Mudat', 'Dirican', 'E'),
	(6, 'Aydilek', 'Kaba', 'E'),
	(7, 'Bleda', 'Atız aksoy', 'K'),
	(8, 'Aygutalp', 'Demirdoğan', 'K'),
	(9, 'Elfiye', 'Keten', 'E'),
	(10, 'İsare', 'Ölçer', 'E'),
	(11, 'Sulbi', 'Erikan', 'E'),
	(12, 'Erhan', 'Nikbay', 'K'),
	(13, 'İlkay', 'Oyan', 'K'),
	(14, 'Özengin', 'Taşkoyan akman', 'E'),
	(15, 'Nursema', 'Arıcan', 'K'),
	(16, 'Bozer', 'Dernek', 'K'),
	(17, 'Lokman', 'Yulcu', 'E'),
	(18, 'Semiha', 'Bent', 'K'),
	(19, 'Kezban', 'Özata', 'K'),
	(20, 'Naime', 'Dirmen', 'E');
/*!40000 ALTER TABLE `yazarlar` ENABLE KEYS */;

-- Dumping structure for table weblog.yazilar
CREATE TABLE IF NOT EXISTS `yazilar` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `katId` int(11) NOT NULL DEFAULT '0',
  `baslik` varchar(100) NOT NULL,
  `ozet` varchar(250) NOT NULL,
  `icerik` mediumtext NOT NULL,
  `yazarId` int(11) NOT NULL DEFAULT '0',
  `eklenmeTarihi` date NOT NULL,
  `hitSayisi` int(11) NOT NULL DEFAULT '0',
  `etiketler` varchar(150) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=latin5;

-- Dumping data for table weblog.yazilar: 100 rows
/*!40000 ALTER TABLE `yazilar` DISABLE KEYS */;
INSERT INTO `yazilar` (`id`, `katId`, `baslik`, `ozet`, `icerik`, `yazarId`, `eklenmeTarihi`, `hitSayisi`, `etiketler`) VALUES
	(1, 6, 'amet adipiscing id amet tincidunt nisl', 'risus porta sed euismod sollicitudin faucibus Nam enim porta a et et id non nec a rutrum vitae gravida Aliquam Aenean sit enim eu tortor Sed tincidunt magna tempor Quisque facilisis', 'et mi posuere pulvinar Proin euismod eu Duis egestas Vestibulum mi ut sollicitudin varius ligula consectetur ornare at quis quam nisl risus mauris tempus pulvinar eu facilisis ante non quis diam ut at tincidunt suscipit sodales ante ipsum purus sed magna eleifend mollis diam scelerisque malesuada sem ut semper massa Donec Nam Etiam cursus porta nibh quis posuere mattis consequat vulputate velit posuere', 20, '2015-12-25', 2020, 'libero nulla Fusce lacinia molestie accumsan'),
	(2, 1, 'dolor eu consequat nibh hendrerit aliquet', 'tellus laoreet ut egestas Donec ac sapien vitae purus odio purus luctus malesuada rhoncus et ultricies elit neque consectetur sodales Praesent id', 'nec semper diam aliquam lectus vel egestas cursus euismod tortor congue Aenean arcu arcu tellus lectus Ut amet massa vitae vestibulum dapibus Nullam purus viverra eget et sollicitudin semper suscipit ante laoreet sit mauris lacus Vestibulum Sed fermentum Aliquam amet tellus placerat quam sagittis pharetra et sem vitae lobortis Aliquam eros velit ut semper est eu Vestibulum', 7, '2015-11-14', 2303, 'auctor turpis quam'),
	(3, 5, 'volutpat non arcu ante', 'tincidunt sit Fusce leo pretium tempor eget In lacus Nulla quis dignissim quis Nunc dolor sed dolor nibh scelerisque libero augue augue', 'ultricies ut Etiam et ut libero felis lorem non facilisis ullamcorper dui ipsum porttitor massa augue a sit amet rhoncus hendrerit metus metus nibh egestas est varius ultricies sit congue eleifend porta auctor Pellentesque Pellentesque interdum Sed suscipit Phasellus vel turpis sollicitudin commodo mollis fringilla nibh auctor lacinia urna nulla molestie a Donec ante bibendum Suspendisse semper laoreet elementum tempor quis mattis sodales Ut dolor aliquet vitae pellentesque amet nisl Curabitur at Nunc ultrices', 9, '2015-06-10', 2460, 'sit lacinia turpis'),
	(4, 6, 'ipsum orci ullamcorper iaculis eros', 'Nullam mi pulvinar Nulla sem eget elementum sollicitudin sed porttitor ligula in a non turpis gravida Aenean interdum justo orci fermentum tempor Nunc', 'rhoncus lectus ultricies varius dignissim sodales suscipit feugiat vel nulla turpis iaculis Proin fermentum Nunc vitae ultricies amet eu eget scelerisque Nunc Etiam euismod dapibus Phasellus et ipsum ac fringilla enim congue odio varius nunc a elit eu sem massa ornare convallis luctus rhoncus Nam diam semper ut nec felis quis sodales neque Donec Vestibulum tortor luctus', 18, '2016-06-17', 2546, 'in scelerisque elementum Etiam vel'),
	(5, 4, 'lacus amet eget dictum molestie Etiam', 'venenatis Ut pulvinar ac at pulvinar Sed dolor varius dui imperdiet dui egestas rutrum massa', 'faucibus risus Nunc mi eget auctor turpis sagittis sit Sed a dapibus tincidunt rutrum elit pulvinar ornare est dolor quam id porta eget at Vestibulum purus sapien Fusce enim ante nec at elementum sem arcu venenatis porta at sit Sed pulvinar sit condimentum nulla justo neque congue Morbi hendrerit vulputate sollicitudin eget Maecenas luctus porta sagittis Quisque nibh ipsum metus eget quam semper posuere quis ac amet et sit dignissim risus nibh orci risus molestie metus turpis egestas justo vitae erat risus a Mauris hendrerit tincidunt et varius quam velit faucibus sapien eleifend sodales at Aenean mattis Quisque', 18, '2016-09-14', 1527, 'volutpat quis Integer a purus'),
	(6, 5, 'viverra aliquam pulvinar massa sapien metus at purus at', 'eget imperdiet lobortis hendrerit justo mauris rutrum ac dignissim eleifend urna dictum nec mauris quam dui id', 'Curabitur augue sodales sed Vivamus erat mauris rhoncus metus iaculis Nullam magna vel est Fusce pulvinar lectus Morbi egestas semper quis metus ut libero bibendum odio pretium Vivamus congue euismod libero id sapien euismod tellus laoreet a ipsum lacinia posuere eu dolor pulvinar dapibus velit risus dignissim euismod dolor vel posuere leo hendrerit adipiscing risus commodo et imperdiet metus ante mi iaculis lorem nisi Curabitur a In sed vulputate condimentum orci sagittis adipiscing tincidunt egestas Ut est et Fusce non', 6, '2015-07-02', 1537, 'nec sodales Proin Aliquam'),
	(7, 7, 'sem ac eros augue sagittis ante turpis', 'euismod lectus mauris dui mollis Morbi sem vestibulum vitae Donec ut tempus auctor enim eget nisi libero quam lacus Fusce orci', 'est sit lorem ac purus id sed gravida libero non porta Vivamus ut sollicitudin dapibus volutpat Vestibulum vitae tristique sed augue nulla rhoncus lectus Donec sit quam eget mattis at augue purus nibh dapibus mi volutpat Cras pretium massa at nec eros tempor at neque mattis auctor Aenean mattis euismod Integer dui metus Donec augue at ut mollis at porttitor in sed imperdiet Curabitur volutpat augue felis Pellentesque Aliquam Proin mattis ipsum porta erat Integer ut in urna Cras Aenean volutpat eros sodales ultricies magna eu rutrum nec a massa mi quis nisi mi felis blandit ullamcorper', 20, '2015-09-02', 724, 'massa nisl turpis eu pretium leo'),
	(8, 1, 'mollis vel Vivamus faucibus libero viverra vitae lacus non eu', 'sit turpis imperdiet sapien turpis mattis at ut convallis consectetur consectetur placerat ligula Sed sodales bibendum elit lacus tempor rhoncus tempor cursus libero non euismod Nulla ante ultricies odio dolor a lacus turpis in', 'Integer ultrices risus Mauris fringilla tempor felis dui mauris fringilla rutrum posuere vestibulum at consequat quis mollis leo enim at pulvinar vel hendrerit a blandit enim Proin erat sed porta nec sem eros feugiat eget at et Ut nisi a aliquet vehicula vel lobortis commodo eu augue dolor id dolor auctor vitae lorem ornare metus pharetra nisi neque lacinia enim', 16, '2014-07-03', 310, 'accumsan augue Aliquam Aliquam'),
	(9, 6, 'mi tempus metus leo gravida metus quis urna', 'Donec varius placerat condimentum In rhoncus imperdiet fermentum sem quis justo erat lacinia at vel massa Fusce leo vehicula id vulputate euismod felis mauris porta lectus posuere laoreet Quisque massa a Sed vitae tellus', 'mauris et et lectus bibendum sed Sed venenatis Curabitur velit arcu libero velit ac sapien odio odio varius feugiat metus ante dui Nullam feugiat scelerisque aliquam ut Nulla orci turpis ante Nullam sit libero aliquet vehicula enim at quis est porttitor dictum non velit neque blandit ut metus erat sed nisl lacinia imperdiet Aliquam laoreet eget at eu porta Fusce pretium elit placerat ante mauris ipsum sollicitudin feugiat eleifend ut Aenean Ut sit dictum felis', 10, '2016-09-21', 2658, 'dictum consectetur semper posuere id'),
	(10, 4, 'tortor molestie pharetra eu arcu Phasellus', 'ac in ut Praesent ornare arcu nunc et tortor a dapibus iaculis imperdiet vel dolor at luctus Vivamus malesuada dolor metus ultrices egestas neque nisl in in neque sagittis ultricies Sed', 'massa Ut ut et ante Maecenas Vestibulum orci ultricies Sed lacus consectetur Praesent aliquet Pellentesque condimentum congue volutpat nec Sed cursus metus leo eu ipsum nulla vulputate non vulputate suscipit accumsan amet libero nulla fringilla amet nisl et erat vehicula gravida tortor est auctor augue et ac mauris Fusce mollis libero erat libero et auctor Duis quis lorem arcu Nulla interdum fermentum amet ullamcorper fermentum quam hendrerit imperdiet Praesent pharetra ligula Ut purus amet mollis ut euismod condimentum sit Proin leo libero Curabitur ante justo Proin aliquam iaculis dapibus Vestibulum malesuada euismod odio nulla sodales', 12, '2015-10-01', 292, 'risus nisl lobortis id'),
	(11, 5, 'vulputate Curabitur auctor Sed', 'ullamcorper quam eget dui Aenean luctus tempus in Sed euismod risus Cras gravida dignissim placerat id nisl eros amet dignissim', 'massa augue vulputate Phasellus diam Nullam molestie mauris sit quis pulvinar vel magna mi hendrerit est tempus erat ligula lectus porta vitae ipsum sed elementum Sed blandit pellentesque nulla mauris at rutrum tincidunt Mauris sollicitudin eget risus rhoncus mattis dignissim a gravida orci et In eros laoreet ullamcorper nec tellus Donec vulputate bibendum eu magna diam egestas volutpat enim varius est amet hendrerit mauris posuere at diam amet nunc', 12, '2014-04-01', 1176, 'malesuada consectetur molestie'),
	(12, 3, 'Morbi rhoncus Nunc sollicitudin', 'a porttitor pulvinar a sodales elementum Quisque sem imperdiet Nulla diam in interdum lacus non condimentum dignissim vel nibh sagittis nisl enim lacus eget a pellentesque laoreet congue tempor Morbi feugiat Ut', 'egestas Phasellus non Nam lorem mattis et nec faucibus egestas erat aliquet eget at enim Nunc mi turpis auctor luctus tempor congue mollis dolor sagittis et ipsum arcu iaculis in dolor at metus Vestibulum bibendum in quis Vestibulum Ut at auctor nunc nisl Fusce risus dignissim dolor venenatis neque placerat consectetur sollicitudin metus nunc a Pellentesque amet Suspendisse a ultrices sem tortor condimentum Cras sem nunc id dui a Etiam eu libero et a Nulla viverra porta at tellus velit velit et Nullam arcu amet Nulla elit nisl nunc', 15, '2014-04-02', 495, 'augue ut sollicitudin in sed imperdiet'),
	(13, 1, 'erat nunc condimentum interdum nibh vulputate ac Ut dignissim', 'massa Suspendisse quis lorem libero Nunc risus ut dictum posuere tortor dolor faucibus at nulla purus est vitae egestas mi quam', 'velit bibendum felis augue pulvinar nisi Vivamus risus lectus vel adipiscing nulla pellentesque Mauris a non justo auctor a felis egestas non in facilisis nec ac erat nibh Ut hendrerit amet Proin libero Ut at velit mi aliquet at pretium sapien non condimentum id mauris in in at at vel Sed consectetur lacus at Donec sem rutrum at id lobortis sem Mauris accumsan varius lobortis quis Nullam tempor malesuada bibendum eget lectus turpis metus nunc enim odio sem nisl metus ipsum', 2, '2015-04-02', 285, 'mollis hendrerit quis eget porta erat'),
	(14, 6, 'mi ac eleifend commodo et mauris Nulla vel', 'augue eu et suscipit pulvinar arcu ipsum vestibulum ultrices sed ornare vitae mattis arcu eget fringilla ut in ut dui metus eget', 'felis at urna at ante bibendum lectus dolor tincidunt pulvinar nec ultricies dui magna libero nisl semper magna dapibus justo Morbi risus dolor feugiat eu lorem aliquam vitae non blandit vitae erat lectus gravida luctus ut Nunc diam vel eu vitae lorem nisi ligula libero Sed porta at auctor malesuada diam risus ut cursus vulputate nec In ut sem scelerisque semper vehicula cursus Donec ultrices leo et vehicula posuere magna accumsan tellus Pellentesque mi ut semper iaculis eget a lorem et egestas eget Nullam posuere Proin Mauris Ut mi Maecenas sapien nec ultricies Donec Sed neque metus imperdiet laoreet', 15, '2015-11-09', 2277, 'non euismod ultricies viverra'),
	(15, 5, 'rutrum sed quis lorem', 'hendrerit libero Mauris amet Fusce commodo urna sit eros in diam odio Mauris Aenean tellus lectus elit elit lectus consectetur ultrices', 'eu tellus pellentesque rutrum cursus non Ut luctus nunc in pharetra amet nec a ullamcorper Sed condimentum velit tortor vitae lobortis lacus eleifend Pellentesque lacinia leo vel scelerisque elit faucibus tristique eu Aenean Cras nisl ut ultrices in Morbi molestie Nunc Nulla tortor lectus ut est Vestibulum semper libero In velit dapibus at rutrum Morbi ut tempor Nulla feugiat semper Nulla pharetra eget erat velit Phasellus lorem risus nec Cras quam nisi in ultricies ultricies in elit at urna purus sit Donec ullamcorper magna libero urna nibh molestie nec consectetur at Duis id nulla', 20, '2015-10-07', 1503, 'turpis purus euismod In felis porta'),
	(16, 2, 'odio Pellentesque consectetur condimentum sit', 'vitae Sed diam amet Fusce Aenean Aenean eget nec pulvinar sit volutpat Cras diam Phasellus metus venenatis Vestibulum Vestibulum Sed libero auctor nunc et augue et placerat tempor tellus Aenean', 'quam quis aliquet mattis tellus Nulla dignissim ac consectetur Proin est tincidunt sollicitudin at Donec at suscipit cursus scelerisque nisl nisi Quisque turpis condimentum Nulla viverra sodales mi pharetra eget Aliquam enim lectus semper tellus tellus id pretium libero varius porta sit hendrerit vitae tortor ac ante eget in accumsan in lectus neque', 19, '2014-09-24', 1809, 'arcu odio ante'),
	(17, 1, 'nunc Vestibulum imperdiet mauris', 'amet suscipit elit Curabitur velit mi sodales Donec turpis risus eu lectus elementum in id ac tincidunt sed suscipit lorem amet at aliquet elit in a varius malesuada molestie condimentum egestas mollis', 'nulla nisi nunc dignissim in id imperdiet amet luctus scelerisque odio eleifend luctus massa Maecenas vestibulum vulputate interdum ac sed leo Aenean arcu Quisque nisl suscipit Nunc sed facilisis elit lacus et nisi sed convallis eu non enim amet Curabitur iaculis Fusce pulvinar vel sed ac placerat amet pulvinar et amet ante adipiscing mattis risus commodo porttitor nunc ut et', 8, '2015-01-06', 885, 'in nulla vitae vitae pharetra'),
	(18, 2, 'mollis euismod dictum risus porta', 'at dui a at nulla dolor Vestibulum euismod et consectetur sit Quisque elementum feugiat mi ipsum turpis', 'sollicitudin ipsum Nunc sodales Mauris vitae aliquet nec viverra dictum adipiscing auctor non sed Curabitur eu pretium ante a Cras ac tristique Praesent scelerisque id ante risus est euismod cursus egestas tortor tellus consequat Ut ullamcorper odio Sed tempor nec imperdiet gravida justo eget commodo nulla consectetur risus vel Etiam blandit est elit turpis sed ut sagittis eu nec mauris risus urna risus eget', 6, '2014-11-24', 1247, 'elementum ante sed enim'),
	(19, 5, 'ultricies lacinia consectetur ut', 'orci libero aliquet placerat Nulla ullamcorper imperdiet blandit orci neque egestas lectus est Curabitur sed congue ornare fermentum Etiam semper tristique nisl sagittis faucibus', 'felis Phasellus semper rutrum elit diam Pellentesque Donec purus est commodo non Mauris dapibus Praesent vulputate pulvinar Aenean ultrices ullamcorper Proin urna lorem nibh ante tincidunt lacinia sed sed lectus porttitor purus ultrices Curabitur nisl nunc ac placerat massa lobortis purus Nulla imperdiet a id eu est rutrum ut dolor mollis ultrices diam tellus pretium nisi urna volutpat vel sodales sodales magna nisl Praesent nec metus faucibus nec justo nulla semper Sed iaculis tristique Mauris interdum ut non blandit eu Cras', 18, '2015-09-11', 1791, 'condimentum augue felis Sed erat'),
	(20, 1, 'eget Mauris lobortis turpis', 'sodales dolor nec magna Nullam urna mi cursus dui tortor massa arcu Aenean sed scelerisque ut lobortis arcu semper odio ac ligula accumsan auctor et mollis tempor vel volutpat diam luctus porttitor ante dui interdum', 'sollicitudin et eget Pellentesque erat sit purus consectetur dictum a vitae ut velit vel fermentum laoreet ante hendrerit Fusce congue porta vestibulum diam mollis fermentum Cras amet lorem ullamcorper dolor in amet condimentum nec iaculis a quam consectetur ullamcorper molestie auctor tortor a dictum accumsan condimentum ornare velit iaculis non congue Aenean vitae a mi ligula ante non eget vitae erat orci consequat non at eget egestas congue dapibus placerat volutpat sed fermentum ac fringilla', 12, '2016-04-06', 2161, 'tortor nec tincidunt mollis Pellentesque ante'),
	(21, 7, 'viverra risus placerat Quisque tempor congue sodales lectus sit', 'eget sed non et accumsan quis in convallis quam euismod a sapien porta justo orci ac id quam feugiat molestie auctor at Etiam augue fermentum augue quis augue leo varius auctor ut', 'id ut purus nisi Phasellus fringilla condimentum ut viverra semper at orci quam nunc porttitor justo sapien fermentum a Suspendisse Sed Nulla velit dui Sed euismod faucibus sapien erat elit condimentum nec rhoncus nulla ultricies Mauris massa ante enim nulla tellus scelerisque at Sed ullamcorper velit sit vitae tortor lacinia eu', 18, '2016-02-08', 355, 'ligula at tortor lacinia mauris Fusce'),
	(22, 1, 'urna tristique justo nibh id sed', 'faucibus quis Donec hendrerit molestie et pharetra massa Nunc pretium sit quis Etiam gravida Integer odio faucibus Nullam ac Praesent arcu non luctus non dolor a risus amet lobortis bibendum Vivamus sit velit lacus', 'nunc metus vitae aliquam Praesent Nulla vitae tristique In ultricies purus volutpat ullamcorper molestie Vestibulum egestas lobortis egestas arcu enim tincidunt facilisis erat volutpat commodo arcu nunc vitae sapien at sit porta iaculis ut Donec vitae gravida Nunc a Ut Donec sit est est augue ut dui augue Fusce risus augue nec accumsan sem dignissim justo magna eu in posuere Praesent amet elit Aenean bibendum sem blandit semper id turpis', 16, '2016-05-10', 404, 'id lorem magna faucibus mattis'),
	(23, 7, 'rutrum dictum risus id fringilla nisi blandit quis id imperdiet', 'pretium hendrerit malesuada condimentum eget magna tempus vel interdum velit at sagittis porta ultricies at Donec pharetra gravida justo id metus in varius ac imperdiet sagittis elit eu congue sapien Phasellus risus turpis Sed luctus', 'hendrerit lobortis eros nunc pretium lobortis dolor tristique tempor sagittis lorem in sed quam varius amet et nec purus ornare imperdiet fermentum a congue Nam tristique placerat ac tempor et convallis tristique Maecenas Duis nisi lacinia hendrerit quam erat sodales Duis elementum eget semper justo velit enim id amet facilisis odio mollis eros rutrum urna hendrerit magna mi nibh in amet id tincidunt a Nulla in vitae vehicula Cras Morbi metus ante erat eget nisl volutpat Praesent lectus purus Donec ac ut placerat tristique quis luctus nec sapien sollicitudin ut quis ut tellus et vel porttitor metus tortor', 15, '2014-09-27', 560, 'Nam a pretium massa ante'),
	(24, 3, 'dignissim ultrices cursus vel libero a lorem amet dictum', 'scelerisque sem ut felis mollis risus vestibulum accumsan non ut rutrum semper vel Praesent condimentum sed id Aenean mauris', 'Vestibulum ullamcorper tincidunt id eget Phasellus interdum porta faucibus purus metus lectus at arcu risus semper nec est tortor turpis Vivamus libero in metus Fusce nunc rutrum posuere eget molestie porttitor et nisi vitae nulla sodales felis tristique nisl et Fusce Sed aliquam tincidunt porttitor commodo Donec eget ac in eros congue in ut sagittis dictum sapien erat nec nunc velit dui amet quam eget Vivamus', 11, '2016-08-29', 2546, 'elementum tincidunt in massa'),
	(25, 1, 'ac commodo est In mollis iaculis', 'Vestibulum purus vel id ac nunc consectetur fringilla in viverra feugiat orci tempor vehicula vitae id sed Aliquam lobortis congue a auctor mi semper diam adipiscing metus', 'venenatis eu urna pulvinar elit quam eu leo Curabitur diam eget volutpat ac ante ligula justo elementum rhoncus purus amet erat nisl gravida pretium nec pulvinar Ut quis quam gravida at sem nulla vel porta justo amet sit Nulla at in Quisque aliquet dolor viverra turpis nisl vehicula justo in magna sed sit', 6, '2015-06-30', 148, 'lacus eros Donec faucibus nisi at'),
	(26, 4, 'a nibh molestie tortor', 'at dui sem congue vel eget scelerisque et auctor urna at vulputate dictum dui porta ac eget Integer at blandit molestie ante tellus tempor lectus', 'lacinia Mauris tellus et eleifend Phasellus nibh Integer quam elit dui Nam mattis tempus sed tortor sit eu Sed Morbi adipiscing vel eget vitae amet sed venenatis euismod enim aliquam porta dolor varius libero laoreet suscipit velit leo ultricies congue Aliquam tristique nibh nec pellentesque amet lectus Curabitur nunc commodo eget Nulla quis nec adipiscing elementum non tortor libero imperdiet magna at nulla tristique nibh sit porta amet orci ultricies faucibus turpis', 18, '2015-08-30', 2324, 'aliquet Morbi cursus ipsum'),
	(27, 1, 'urna ultricies arcu tristique libero', 'facilisis elit at Curabitur gravida tempor imperdiet Aliquam sed Mauris ultrices ipsum ipsum elit et at egestas leo nunc eu diam iaculis a Donec et vitae leo mattis nisi diam ipsum', 'scelerisque rutrum eros nibh sit molestie leo ligula accumsan luctus tortor ut Duis justo at dapibus tortor vitae euismod enim Phasellus tortor mauris nunc elit dignissim euismod hendrerit luctus placerat malesuada massa est ut a tincidunt Phasellus velit Cras eu mi et sagittis tempor posuere convallis enim id eu nibh nisl ligula non diam hendrerit tempor vel ultricies luctus at sagittis sit dictum nisi lorem ante odio condimentum purus Sed quis metus tristique viverra eu non libero ullamcorper dui elit faucibus tincidunt gravida ut placerat lectus', 7, '2016-09-08', 148, 'semper Vestibulum quam bibendum'),
	(28, 2, 'egestas eget ut sapien id Nam Ut commodo egestas a', 'dolor libero Sed lacus at accumsan sit sollicitudin ut Duis facilisis Morbi convallis metus metus ipsum non dictum quam faucibus imperdiet Ut arcu mi turpis arcu Proin Proin nec egestas Donec lectus sed bibendum nec', 'neque Donec vehicula venenatis non pharetra justo dui Sed in Nullam mi non bibendum Aenean diam nec vel nec congue quis sagittis sollicitudin sapien eleifend risus ipsum molestie ut a ultricies sem eu dolor Donec sollicitudin Suspendisse leo Vestibulum eu Pellentesque Sed vulputate velit sit In mattis egestas eget nibh risus tortor metus Curabitur urna eget nisl leo tincidunt vulputate sapien auctor ut lorem porta ut vel nunc fermentum felis diam porta dolor eget adipiscing tristique convallis tortor commodo sit blandit', 12, '2015-01-02', 2392, 'nibh mi Curabitur id viverra'),
	(29, 5, 'fringilla eu eget dolor at nisi sapien', 'amet congue libero id pharetra id nisl Praesent cursus volutpat ante eget eros vel sed consequat imperdiet pretium', 'ultricies porta nibh lobortis Fusce magna Sed nisl lobortis odio eget nulla varius augue posuere velit eget tellus enim molestie in in blandit condimentum lorem Fusce pharetra suscipit sapien euismod aliquam erat ut congue imperdiet nunc dapibus lorem et auctor ornare Ut nisi nec congue malesuada accumsan Maecenas nunc magna suscipit augue sollicitudin vel erat in varius ut Praesent blandit in arcu id eu in laoreet condimentum sagittis mollis odio vel justo elit dapibus nisl nisi nisi dignissim tincidunt nisi nec elementum dolor dolor at iaculis', 14, '2016-08-30', 151, 'faucibus elit faucibus ultricies'),
	(30, 5, 'id Vestibulum risus mauris non placerat Integer mollis lobortis Duis', 'at sit a sed rutrum non arcu sollicitudin tortor scelerisque lectus a Vivamus ipsum Vestibulum in eget auctor Quisque arcu urna sed quam at purus turpis mollis et aliquet purus', 'tristique cursus condimentum placerat amet lorem et Praesent commodo nec non Pellentesque vulputate Curabitur id mauris Proin tellus hendrerit metus risus orci arcu nec tortor pulvinar nisi risus tellus convallis ac at placerat elit eros faucibus nunc malesuada Nullam risus in Nunc at vitae metus Etiam ullamcorper velit urna Quisque lacinia lobortis eu eget a congue eget quis ante tortor scelerisque bibendum id nulla in sit nec dui consectetur augue imperdiet auctor vulputate nisl Cras suscipit lectus metus purus eu lectus Integer vitae Mauris dictum', 10, '2015-10-14', 2269, 'mattis Nullam mauris dignissim porta'),
	(31, 5, 'malesuada aliquet porta placerat mauris velit volutpat Donec eget', 'nibh in dolor Phasellus imperdiet risus ipsum a Aenean odio est urna et in placerat vitae Etiam eu erat ultrices dictum erat ante Vestibulum lorem Sed', 'tortor amet mi non id dapibus vel in fermentum turpis facilisis lorem Sed placerat metus nisl eros mattis Mauris dolor adipiscing faucibus id orci nulla porta tellus pulvinar mattis dolor facilisis quis elit vel purus volutpat metus tristique a non adipiscing scelerisque vel Quisque congue nulla id Sed tellus felis porta nunc at lacus velit eu at bibendum aliquet vulputate malesuada dolor auctor sodales sed est aliquet vel sit scelerisque elit sit viverra justo in scelerisque gravida Donec leo', 3, '2016-08-10', 2365, 'sit Ut ut amet velit'),
	(32, 5, 'risus at hendrerit feugiat porta metus Mauris Nullam urna', 'nec Fusce blandit eget id dolor nec tempus lectus malesuada ultricies eget pulvinar quis pellentesque imperdiet tincidunt congue sed', 'et rhoncus egestas tempor dignissim sit turpis augue sed adipiscing Curabitur sagittis id suscipit Nam quam et Aenean magna eu convallis auctor massa eget nec cursus rutrum ut elementum sit Maecenas mi felis velit purus at tristique metus id lectus Etiam porta elit diam arcu ut nec elementum In ac velit faucibus dolor nisl lorem at tellus in pulvinar iaculis lorem in ultricies egestas rhoncus amet quis fermentum Donec Proin Nunc ipsum tellus rhoncus ipsum Nulla mauris magna Etiam Aliquam magna pretium suscipit mollis urna odio lectus posuere Donec mollis sed placerat in tellus hendrerit', 9, '2016-05-29', 2946, 'at nec neque ut ut'),
	(33, 5, 'Donec dui consectetur id aliquet eget quis vehicula id justo', 'Praesent dictum non mollis a vitae et elit et consectetur Fusce eu pulvinar semper mauris arcu rhoncus quis sodales amet Praesent nunc', 'Nulla ligula augue eget in metus Integer commodo nisl egestas scelerisque dolor tempor erat imperdiet tellus ac Duis Integer dui at Suspendisse lectus volutpat at tortor convallis non nunc pharetra Sed id non dapibus amet tempor sapien tincidunt interdum euismod Nullam libero nisl Etiam et vel aliquet scelerisque tortor tincidunt eget', 10, '2015-06-05', 495, 'nec turpis eget adipiscing justo'),
	(34, 5, 'fermentum ante tempor ac ac a eget nibh massa enim', 'eros Proin ut id nisl id eros et mauris non pharetra quis Proin Pellentesque Integer nunc pulvinar porta felis', 'ut vulputate purus lectus Praesent elit id bibendum tempus Aenean amet vel eleifend eros Proin a nisl sapien quam in metus vel ullamcorper id eros lorem nunc at ac amet Quisque sit id nulla ultricies nisl ante vitae vulputate mollis diam sapien orci ac libero vulputate quam vel odio sed arcu id consectetur metus auctor massa nunc eleifend nec quis hendrerit tristique turpis non purus Mauris pellentesque tempus neque Praesent dolor ultrices orci Aenean mauris orci lorem magna bibendum ornare tellus Fusce turpis a faucibus tortor facilisis mattis nunc', 17, '2015-12-26', 1009, 'felis dapibus sed eu'),
	(35, 3, 'bibendum justo fringilla nec non mollis Praesent', 'aliquet nisi rutrum vel fringilla Phasellus amet orci est odio libero venenatis mollis scelerisque neque ipsum dolor elit nisi eget felis neque nisl ut mauris urna tellus metus tincidunt a semper eleifend Integer sodales', 'nibh urna nibh augue mauris elit quam Donec sapien fermentum elit sodales justo leo sapien dapibus tristique tellus dictum quis fermentum tincidunt velit vel Quisque dolor neque arcu quam sem luctus volutpat sit ipsum pulvinar et elit in ornare Nam consequat consequat mattis nunc porttitor eleifend Duis elementum Etiam porta dolor purus ac aliquet in eget ligula justo in ultricies erat sit eu a Duis purus Vivamus ante a erat Morbi quis Vivamus sit nisi ipsum nisl sit Donec mollis nisl in sollicitudin turpis ligula Vestibulum', 12, '2014-09-17', 1710, 'enim placerat ac leo euismod interdum'),
	(36, 4, 'massa elementum vel Aliquam ut sed amet turpis Sed', 'bibendum rutrum neque eget nibh eros Pellentesque lectus ultrices tristique sed Integer nulla laoreet vel Proin feugiat Phasellus tristique quis turpis at facilisis eu vitae elit at Donec ac condimentum sit id', 'congue at id Curabitur Curabitur Mauris pulvinar in imperdiet ac massa sodales ac viverra Integer sit mattis enim vulputate gravida ut tristique velit augue nulla dignissim tellus augue eros vulputate sed Nunc tincidunt sem ac imperdiet egestas faucibus magna non eleifend viverra euismod sagittis ante elit ultrices sed nisi Etiam euismod ipsum iaculis eget sit nec sapien hendrerit vel', 14, '2014-08-29', 2083, 'pellentesque magna vel metus eget'),
	(37, 2, 'a sed eu vestibulum Integer rhoncus Phasellus pulvinar Proin', 'turpis pulvinar ligula urna non Vestibulum id tincidunt Nunc tellus eget sollicitudin accumsan turpis eu velit eget tortor euismod feugiat eget hendrerit suscipit at diam at at', 'sapien lobortis odio mattis porta urna nulla et semper sit nisl iaculis condimentum a arcu Curabitur Duis massa semper tincidunt consectetur eget erat massa porta id dictum quis bibendum tellus justo Curabitur ut nec id sagittis tellus mauris vitae consectetur bibendum aliquam risus vitae In sem quis sem nulla sit imperdiet accumsan tortor nibh semper mauris scelerisque pretium sem pellentesque quis nibh a fermentum nisl eu feugiat erat interdum non amet ac sem Nullam fermentum arcu lectus Aliquam fringilla a nibh nisi arcu id Sed eu', 7, '2015-07-21', 936, 'mi tempor lacinia Praesent lacinia lacus'),
	(38, 3, 'ac Cras lacinia massa risus sapien', 'dolor enim et eget ut lorem in velit nunc hendrerit scelerisque vitae sit egestas a lobortis sit dolor Proin', 'eu sodales gravida dolor vehicula non malesuada erat elit vulputate turpis elementum Etiam id amet rutrum massa mollis metus lorem id semper ac risus ut tincidunt nunc lacus convallis aliquet elit a velit vitae nisi tincidunt posuere id ut lorem Pellentesque a non metus blandit arcu pulvinar sagittis ac in augue ultrices blandit lacinia in Maecenas porta a vel tellus ullamcorper ipsum scelerisque ipsum orci faucibus pulvinar sit ultricies faucibus et Vestibulum libero sodales diam diam Donec sollicitudin elementum imperdiet eget justo elit sem nisl quam', 5, '2016-06-05', 1546, 'convallis Vivamus urna'),
	(39, 4, 'lobortis adipiscing arcu sed dictum pretium', 'varius sagittis et dictum nec ullamcorper interdum tempor mollis metus libero velit amet elementum scelerisque dapibus nunc lectus non convallis enim libero risus tristique erat turpis justo metus at sollicitudin erat Cras', 'ullamcorper ante Curabitur bibendum placerat turpis porta Curabitur sit placerat Ut Phasellus pharetra iaculis aliquet pellentesque odio id sit lectus nec quis blandit Nullam risus sed nisl Suspendisse tempor lorem lacus sem enim nisl erat Donec at Proin Ut condimentum Sed Aenean Vivamus ultricies eleifend sem ac orci a eleifend', 4, '2016-04-27', 295, 'auctor mattis tellus elit'),
	(40, 7, 'lorem lobortis vulputate Mauris', 'augue fermentum hendrerit non odio tempus Nulla interdum et Curabitur erat malesuada scelerisque magna est vulputate accumsan et in non ac aliquam dui purus Maecenas fermentum Cras augue Fusce odio quam eu mauris at', 'Ut iaculis est Vestibulum mollis Sed Aliquam malesuada arcu tellus Pellentesque elementum molestie vehicula mi purus nulla libero erat Integer a eu Duis non sollicitudin et nisi amet et pellentesque consequat dignissim Duis nibh amet posuere ante et purus erat felis convallis placerat amet consectetur tellus tempus vitae neque odio dictum ut at porta Sed eu justo sollicitudin rutrum rutrum sem sed sit amet porttitor at augue dolor volutpat amet Ut Pellentesque lectus Donec aliquam facilisis Maecenas ac et non metus dignissim consectetur lorem amet vehicula lobortis amet et', 15, '2015-02-04', 711, 'lobortis dolor Donec fringilla pretium'),
	(41, 1, 'in quam elementum diam blandit Etiam at scelerisque', 'facilisis sit at mi venenatis tempor Sed tincidunt eu velit Integer id amet ultrices convallis Ut rhoncus interdum justo amet dui In Sed commodo mauris a nisi sapien Vivamus lacinia quam non accumsan', 'pulvinar vitae id congue mauris gravida gravida at bibendum sit sed purus mattis cursus est Morbi erat at elit eget Vivamus elit semper justo tortor elementum a ullamcorper luctus aliquam eleifend ante porta libero mauris eu lectus lectus odio tristique rutrum mollis molestie at metus luctus Ut facilisis eleifend cursus elit Etiam est non lectus euismod ultricies est lacus dolor vel Morbi Duis hendrerit sem sem volutpat accumsan lobortis tortor metus sed orci condimentum ut id bibendum consectetur at quis sit bibendum a mi placerat ultricies et iaculis placerat sit', 10, '2016-09-30', 967, 'luctus magna Phasellus tincidunt at'),
	(42, 1, 'mi nisi pharetra quam egestas imperdiet bibendum imperdiet', 'sit ut in suscipit eget ornare In et porttitor mauris accumsan mollis elit convallis quis pharetra quis nunc felis Integer dignissim arcu justo', 'eu pulvinar dui imperdiet pulvinar dignissim vestibulum aliquet ipsum justo sit lectus nisl sollicitudin velit eget mollis vestibulum ac gravida id hendrerit Cras dictum ullamcorper felis Phasellus Duis Mauris viverra eros arcu aliquet hendrerit purus commodo Curabitur cursus arcu in eget gravida sapien In eget Suspendisse Duis ultricies augue Ut nec nunc bibendum Quisque bibendum arcu tempor sed lacus auctor diam quam neque quis amet arcu tortor mattis quam leo interdum enim sem nunc non venenatis dignissim id tellus semper commodo scelerisque elit Morbi Morbi sollicitudin lectus vestibulum', 17, '2015-06-15', 418, 'sed nec justo eleifend'),
	(43, 4, 'nibh sed et nibh ut dolor', 'vel bibendum lorem hendrerit nisi semper nulla adipiscing porta dui id quis tincidunt Suspendisse id libero', 'nec elit vehicula sem facilisis sit mi mollis quam imperdiet sit nisl auctor neque Sed congue iaculis nisi pulvinar vulputate libero convallis leo eget amet libero Curabitur elit ut metus commodo risus ullamcorper quis congue Curabitur pulvinar vestibulum Sed ut ut Sed Integer Aenean ligula turpis nisl est massa sollicitudin metus molestie Curabitur odio quis metus sollicitudin quis Fusce vel Mauris eros mattis Phasellus eu sagittis condimentum quis mauris euismod', 7, '2015-03-15', 1065, 'consequat ante orci lobortis'),
	(44, 7, 'Ut vestibulum Maecenas venenatis Curabitur eget', 'lorem sagittis scelerisque malesuada mollis risus eget diam nisi vel Quisque ligula diam blandit nibh sit felis Fusce cursus leo nec metus Cras molestie Quisque sapien sem Nam tellus a Ut varius', 'tincidunt vitae rutrum sem sodales Maecenas erat molestie est neque id porta metus nec justo imperdiet Donec quam iaculis ante Donec euismod sed massa molestie ornare metus nec porta lacinia arcu euismod vel odio ullamcorper Donec Etiam eget est vehicula purus nec vehicula Proin id Phasellus ac porta lectus a sit quis nunc tempus metus quam risus molestie semper urna nunc mi libero porta Nunc mauris ligula neque mollis ut nisl Aenean tortor massa lorem molestie volutpat sodales Aliquam fringilla odio ante Mauris ullamcorper pulvinar et consectetur in fermentum condimentum', 9, '2016-08-01', 689, 'sed massa eros'),
	(45, 7, 'Fusce dolor hendrerit nec', 'enim sollicitudin cursus vel Sed velit Duis tincidunt lorem Duis non orci id turpis hendrerit commodo nisi ligula interdum nibh vel vehicula vitae Nulla et amet risus', 'Duis tellus nec sodales sed malesuada turpis Aenean vestibulum ullamcorper Fusce Suspendisse Sed vitae ipsum lacus Nullam quam ante eleifend a eros quis sed Sed Praesent ipsum sagittis ante malesuada mi augue bibendum convallis congue id ut quis aliquam consectetur turpis rutrum quis Praesent tincidunt lacinia gravida vitae at metus erat sem leo tellus malesuada at sem nibh ut vitae nulla dolor metus ante eget est tortor interdum id pretium amet eget ac fermentum scelerisque placerat est nisi ullamcorper Aenean sed Proin vulputate Pellentesque ut tincidunt porta', 11, '2015-11-27', 701, 'risus ut pulvinar fermentum gravida'),
	(46, 7, 'imperdiet fringilla augue risus Curabitur euismod aliquam Phasellus', 'tortor Cras semper neque amet ante a Nunc cursus Nullam est nibh ut ut Aliquam', 'sollicitudin tellus ac Duis tortor facilisis Nulla dolor Fusce urna Praesent at at ultricies sit massa eu at ipsum sed volutpat leo ante erat ultrices porttitor malesuada at ut pellentesque Nullam lacus lectus rutrum suscipit lorem dui congue pharetra lorem turpis quis Nulla interdum ut lobortis imperdiet eget semper nunc tincidunt Sed eget purus mollis imperdiet nibh dignissim vehicula eros sagittis ut Aliquam consectetur arcu auctor Cras nec leo Nunc vitae sollicitudin eget et vestibulum fringilla vel quis porta tellus tortor sodales dapibus purus erat fermentum rutrum nisl metus non in amet et eget volutpat', 13, '2015-02-04', 1479, 'Etiam ultrices purus dignissim'),
	(47, 2, 'blandit at ut nec eu et eleifend', 'odio nisi lectus quis felis metus faucibus Suspendisse elit sagittis tellus volutpat felis semper accumsan molestie sit suscipit sodales porttitor amet vulputate lorem placerat orci porta Curabitur', 'ipsum luctus nec cursus ac aliquam consequat vehicula sagittis sed luctus sed eu nisl eu Donec ut non viverra tellus a Integer lectus sit Fusce porta eget cursus nulla turpis orci eros mi Maecenas in lorem nec metus sem fringilla amet vitae diam varius tempor eu quis elit auctor molestie Ut dolor sit nisi augue enim mattis mattis eu massa eros eu Praesent eu Integer Suspendisse nunc aliquam eleifend sodales nibh in in dolor sed pharetra molestie risus diam Sed Morbi lorem ut Vivamus', 2, '2016-09-20', 1152, 'Fusce mollis enim consectetur euismod justo'),
	(48, 3, 'est sit vel scelerisque mi fermentum varius', 'eleifend Phasellus posuere vehicula Sed gravida scelerisque Vestibulum Integer at Mauris sodales faucibus dignissim vestibulum scelerisque metus iaculis rhoncus volutpat lorem faucibus feugiat odio Donec odio Nunc', 'congue venenatis sodales aliquam aliquam dolor volutpat quam Etiam Quisque urna ullamcorper non at at vel est erat at Praesent commodo at convallis quam et Curabitur Proin vitae dignissim sodales scelerisque fringilla est accumsan sed Praesent malesuada id ligula Fusce rhoncus in auctor quis sagittis lectus id hendrerit mattis ipsum Aenean eros tincidunt felis imperdiet eleifend tortor nunc lectus mollis egestas massa quis Nulla libero suscipit', 16, '2016-01-03', 147, 'vitae elit hendrerit Sed'),
	(49, 1, 'risus mollis tortor consectetur risus ante diam Curabitur', 'et et eros sed massa ut quam lobortis neque lorem augue ipsum mollis nibh tincidunt in nibh mollis quis placerat turpis et vitae lorem nunc amet metus sagittis fermentum', 'elit posuere orci amet quis auctor Nulla tempor nisi at elit orci Nulla Aenean leo eget quis accumsan Phasellus iaculis amet libero posuere Nullam Vestibulum bibendum elit amet pellentesque pulvinar mollis at odio vel neque a rutrum ut nec Quisque eget quis Sed feugiat Maecenas libero eu ipsum ornare varius in ipsum semper ligula nec elementum ipsum mauris nunc Nunc id orci ipsum nec Fusce libero purus at nulla eget et mi Fusce adipiscing gravida Aenean ut urna Nulla Aenean condimentum Curabitur odio Sed in orci non ultrices ac metus scelerisque odio vel mauris neque sodales', 18, '2016-09-11', 1676, 'Sed urna eu pretium lacus vulputate'),
	(50, 7, 'lacinia aliquam Vestibulum odio quis massa orci ante vitae', 'ante iaculis hendrerit neque accumsan Fusce lobortis non malesuada Donec nec metus sed nisl ligula sollicitudin id sit at augue tellus erat Cras sed volutpat condimentum In iaculis Morbi Vestibulum Sed imperdiet nunc et', 'condimentum ut tellus at Pellentesque odio nisl consequat molestie Sed neque ac leo mattis orci scelerisque Duis leo quam sapien at neque cursus risus eu eu blandit Vivamus consectetur dolor gravida vulputate sem neque mauris in sapien amet euismod mi Cras Morbi nulla Cras ullamcorper enim Phasellus in metus consectetur ligula Mauris sit et euismod purus lacinia mauris libero viverra tempor tortor Quisque ligula Sed convallis faucibus non dapibus augue odio ac', 4, '2014-09-07', 2347, 'at a arcu vulputate ut'),
	(51, 4, 'commodo leo Nunc laoreet', 'nisl tellus Etiam et eu ultricies leo leo dolor ante tincidunt non Vestibulum lacinia sed facilisis tempus dolor varius egestas et hendrerit', 'lacinia tempor dapibus ante ac est ut eget pretium et a id lacus Mauris ante feugiat quis in volutpat purus massa adipiscing Sed accumsan Integer in eu lacinia eleifend Sed est amet aliquet diam quis a iaculis nulla imperdiet varius nec aliquam Phasellus condimentum aliquet tellus justo diam amet porta mauris nec vestibulum mollis leo enim vitae tortor eleifend feugiat ipsum in velit laoreet sit a Nulla at mi in Curabitur vitae risus rhoncus urna pulvinar sodales in suscipit et elit magna iaculis scelerisque sed at et metus', 3, '2016-07-30', 894, 'nunc quis amet sem lorem Nullam'),
	(52, 4, 'in dictum hendrerit orci eget faucibus Sed adipiscing sed elit', 'tempor lobortis Maecenas vehicula amet justo Phasellus Quisque Suspendisse a ut Nulla sem non Donec amet felis vitae egestas libero lacus blandit luctus Proin Ut eu vulputate vitae', 'ullamcorper metus Proin metus ut Nunc sagittis laoreet porta dolor porta Quisque Nunc vel Praesent a Sed Donec gravida leo gravida magna quis sit orci Donec rutrum molestie eleifend Nunc vulputate interdum pulvinar fermentum lorem enim vestibulum viverra quam dignissim egestas nulla at nisl augue mattis aliquet neque nisl nec eget venenatis id Nulla vel', 19, '2015-11-26', 1173, 'felis at ipsum Pellentesque urna'),
	(53, 2, 'ipsum arcu tempor vulputate dui Phasellus', 'Vivamus leo In lectus tincidunt quis vestibulum metus Nam eu auctor commodo interdum id ac bibendum arcu erat non non Morbi dolor eget', 'suscipit lacinia et tempor vel vitae Integer vitae ut ut Fusce at Nam condimentum dolor porta Mauris imperdiet eu vestibulum at Nulla placerat faucibus nec nunc erat enim elit sapien eros eu nunc urna sed ipsum egestas mauris at et est amet quis sit massa nibh Aliquam in Phasellus augue lectus imperdiet turpis Proin tincidunt vulputate at felis diam eget cursus mi Donec egestas massa at Aliquam hendrerit Aliquam id orci dolor Mauris Vivamus eros bibendum luctus pellentesque', 14, '2017-01-28', 1873, 'dolor bibendum neque'),
	(54, 6, 'convallis risus malesuada sit leo Morbi neque mauris eu eget', 'Vivamus elit massa lacus eros quis eu sodales Quisque lectus nisi congue lectus pharetra justo in eu dui', 'sollicitudin id sagittis cursus Curabitur Praesent vehicula luctus sapien odio lorem euismod ante massa pretium ultricies amet sagittis dictum felis sem et ultricies velit cursus Quisque pharetra amet sem Vivamus non velit quam lacus cursus felis porta nec pellentesque aliquet tortor sit Morbi nisi lacus ut purus Fusce Vestibulum tempor justo est turpis aliquam Pellentesque eget ac Mauris et eget purus orci nulla imperdiet Vestibulum purus condimentum', 7, '2015-09-08', 2715, 'interdum vitae in ultricies arcu Etiam'),
	(55, 4, 'amet at massa sem a vitae feugiat', 'auctor eget aliquet mollis ut vitae Morbi eget eu bibendum imperdiet eleifend sed sem placerat auctor nulla ipsum', 'mauris Mauris pretium sed et porta mi malesuada congue eget id nisl Aenean hendrerit eget sollicitudin sapien et quis lorem Mauris vulputate sem semper mauris arcu rutrum diam sollicitudin massa urna aliquam condimentum nulla odio amet at lectus massa nec velit cursus et amet nec tincidunt Mauris porta arcu porttitor eu posuere congue ornare Donec faucibus porta Nulla purus tortor tincidunt porttitor Cras Mauris sit in purus felis Quisque Cras velit arcu ut non Aliquam placerat cursus viverra nibh orci in non pulvinar accumsan placerat sodales enim ultrices lacus non vitae Morbi ante Fusce tortor', 4, '2017-01-23', 920, 'bibendum leo Curabitur aliquet egestas Etiam'),
	(56, 5, 'erat in lectus sit luctus sagittis elementum', 'id molestie at ut erat in dui pellentesque Integer non a amet augue dapibus mattis id', 'erat nibh bibendum dolor luctus pharetra libero laoreet justo ante justo dolor tortor quam scelerisque sollicitudin eu Nulla Maecenas non tincidunt Vestibulum auctor Nulla ultrices ipsum viverra semper gravida bibendum mattis massa Donec nec tortor congue cursus tempus sed lorem ipsum eu sit erat tempus blandit dignissim turpis lobortis Aenean lorem arcu egestas ut nec vitae nulla nunc Nam nisl consectetur diam varius eu lectus sed ante ac Aenean Phasellus malesuada dignissim amet vulputate mauris euismod sit nec nec nec velit semper Nunc Morbi tempor Aliquam at a leo leo Ut odio Nulla Praesent', 15, '2015-07-03', 2770, 'magna augue feugiat'),
	(57, 1, 'Phasellus erat elit sed', 'eu massa ut amet sapien pellentesque odio consequat felis sagittis at convallis in est sit mi eu id felis non iaculis mollis consectetur tempor nunc suscipit ut Phasellus', 'ullamcorper Donec gravida dignissim mi amet venenatis sem tortor Aliquam Aliquam pretium euismod Cras sollicitudin dictum consectetur eget arcu convallis augue ante eleifend mollis erat porttitor vitae sit et sed sem pharetra felis nibh Ut ligula pretium molestie condimentum a bibendum semper turpis metus sollicitudin et nibh porta et at tempus congue ante sapien ut sagittis sit malesuada eget dictum et', 13, '2016-04-22', 2661, 'porta a at adipiscing massa'),
	(58, 6, 'Duis Nunc tortor vitae velit', 'sapien ut nulla eleifend tempor leo nisi sapien mi a neque elit mauris et eleifend eleifend vitae justo dictum et metus lorem quis lacinia laoreet faucibus rutrum semper Morbi euismod lacus eget porttitor mi', 'fermentum tellus sit mi nibh Suspendisse enim congue at interdum arcu et porta porttitor Nullam metus volutpat at mi luctus nunc nisi accumsan tortor a metus dolor venenatis Sed velit eget nec amet sem at sed volutpat mauris Aliquam ultrices Vestibulum bibendum interdum at amet ligula fringilla Nullam vitae porta condimentum id euismod bibendum mi Cras pretium adipiscing', 8, '2014-08-30', 2961, 'fermentum pellentesque tortor sed'),
	(59, 5, 'erat dolor felis condimentum Maecenas Cras sodales', 'libero Nulla dictum pulvinar sollicitudin Etiam euismod fringilla Donec tempor at at velit semper congue nisi ut tincidunt sed pulvinar libero et egestas', 'diam sollicitudin sagittis Suspendisse nec et vitae ligula consectetur a a ultricies eu velit nibh diam dictum tortor ante Phasellus nisl aliquet Nulla dignissim ac egestas In accumsan mattis Cras a Vivamus sed at luctus tortor Donec Donec lacinia enim Pellentesque rhoncus condimentum in Etiam orci eu eget Nam placerat pulvinar sodales Quisque Praesent egestas augue In ligula ultricies dapibus velit Proin Proin tortor aliquam ut purus nibh Integer sem sollicitudin malesuada orci sodales metus non et at iaculis mauris Nam in pharetra libero et a tortor aliquet id Curabitur placerat dolor massa', 15, '2016-07-14', 2958, 'at porta Etiam quis'),
	(60, 1, 'ligula Proin Nulla Vestibulum Mauris condimentum', 'ipsum vel in non quam massa vehicula lectus erat ac leo arcu ligula rutrum metus purus ut ac congue non', 'at Nam iaculis eget sapien tortor augue diam nunc lacus fringilla luctus turpis nisl Nulla est feugiat nec dolor at sollicitudin erat et tortor scelerisque vulputate Nulla sed tincidunt ante enim at ante ornare odio posuere diam ac euismod malesuada magna neque iaculis Proin erat consectetur fringilla leo eget at Nunc bibendum volutpat Duis ac Curabitur eros Proin interdum dignissim massa semper nulla imperdiet enim Maecenas ut sed Vivamus sed nibh Nulla a nec Donec sodales Vestibulum rhoncus posuere interdum Nulla et auctor ante luctus Etiam eget posuere ut libero laoreet bibendum Fusce tempor', 18, '2015-11-02', 855, 'lobortis varius velit'),
	(61, 6, 'eget laoreet convallis non volutpat lectus vulputate Etiam quam Sed', 'bibendum urna urna elit augue molestie ligula libero sit sapien varius convallis in sem quis Suspendisse porta nibh fringilla', 'tincidunt velit convallis nunc vel risus eget leo Nullam quam placerat velit ut a at congue amet lectus nisl condimentum vel mi quis congue sed augue molestie vestibulum ac et Vivamus sodales dolor mollis euismod a lorem sollicitudin Praesent dolor ut ut laoreet nunc Etiam Vestibulum Donec egestas Nullam porta Donec turpis nunc Curabitur arcu lobortis tortor venenatis Duis commodo non varius metus vehicula leo bibendum vitae felis libero pretium dui tristique pulvinar cursus ut at pretium feugiat porta ut sed vehicula Integer sed sem eu sollicitudin nisl laoreet ante aliquam vel non Proin nisl faucibus porta', 2, '2017-02-09', 890, 'aliquet semper molestie dolor'),
	(62, 4, 'velit imperdiet Donec leo', 'nisl dolor tristique quis dolor Phasellus velit ut dolor in a quis dictum nunc Suspendisse quis hendrerit quam', 'vulputate nunc bibendum pellentesque id neque amet non tellus amet massa sed dolor lacinia non posuere orci viverra sit cursus lacus sem vitae nisi congue leo dapibus tortor volutpat Vestibulum nisi a eleifend erat mattis quam et Vestibulum ac purus Pellentesque accumsan tincidunt eu ante eu sem Nam lectus metus dapibus erat mauris Nunc mi a adipiscing nec urna turpis vel iaculis eleifend urna accumsan Sed ullamcorper mi blandit vitae metus Phasellus non', 18, '2016-08-24', 664, 'quis ac mollis'),
	(63, 2, 'Praesent nec amet purus risus magna vestibulum', 'nibh vel elementum metus sollicitudin nulla id In euismod semper vitae eu risus id Curabitur Suspendisse magna eget ut semper orci tincidunt Suspendisse sed nisl diam ut metus Nullam', 'non pulvinar elit semper sem justo nec arcu et eu tortor eu Aliquam semper elit mauris eget neque tincidunt tempus et est Nulla Curabitur sodales amet amet enim Proin vel pretium iaculis pulvinar nibh dapibus fringilla felis est sed quis in tempus congue arcu lectus nec In eu rutrum molestie eget sodales imperdiet lorem mattis pulvinar condimentum dictum interdum interdum molestie nunc porttitor augue Suspendisse Quisque auctor eu amet augue luctus sapien auctor dui fringilla neque nisl Nunc dictum In in ullamcorper ante', 1, '2016-06-30', 2789, 'Mauris dignissim luctus euismod'),
	(64, 1, 'malesuada lacus augue et mauris vehicula amet', 'ante dignissim eget nunc porta arcu dictum elit lobortis sed hendrerit eu Vestibulum pulvinar Pellentesque nulla Maecenas mauris quam lorem lorem et leo amet nisl lorem', 'iaculis placerat Sed elit eget In sed tortor et metus mi metus magna non Nam orci scelerisque justo vel hendrerit non nunc Sed mollis auctor congue in nisi Suspendisse varius non dolor Duis elit vehicula ac vitae metus faucibus augue Pellentesque Nunc molestie imperdiet iaculis placerat dignissim leo neque sed at vel at semper nisi nibh lorem', 16, '2016-11-28', 1185, 'ut sapien Donec aliquam et ultricies'),
	(65, 4, 'ipsum ultricies eu ut et sagittis eget turpis condimentum', 'rhoncus congue imperdiet nisi hendrerit purus accumsan Ut felis et et vulputate in Ut molestie ultrices feugiat Donec vitae vitae', 'magna nisl Donec lectus luctus quis dui ultricies dui convallis vulputate purus ut felis laoreet nunc Pellentesque sed eu nisi felis Sed pretium non metus tellus sem sodales ornare eu sollicitudin Vivamus nulla eros euismod accumsan Aliquam Nam adipiscing neque malesuada sed leo ipsum nulla rhoncus odio dui Quisque tellus ut egestas fermentum tortor urna elementum blandit a pellentesque vestibulum id Cras augue quam purus mollis libero purus varius nisi fringilla convallis Vestibulum Nam lobortis condimentum vitae id porta porta Integer nibh commodo feugiat', 1, '2016-01-04', 2210, 'accumsan malesuada vel Donec Praesent Integer'),
	(66, 6, 'Donec ut vel sem lacinia fringilla ornare', 'Duis condimentum massa purus enim dignissim posuere nisi quis dapibus pretium porta dolor sit Maecenas suscipit viverra imperdiet', 'vulputate sit commodo Mauris tristique placerat faucibus mi ullamcorper eget viverra rutrum non et Phasellus Duis tempor nisl tempor diam id id eu Mauris tempor bibendum vel velit vestibulum nec erat massa ut pretium sit non mauris Vivamus non interdum Fusce nunc Donec Praesent diam Nunc fringilla lacinia turpis felis metus et mauris metus et quis felis aliquet dolor laoreet sagittis in dui lorem dui mauris tincidunt commodo arcu porta arcu turpis tincidunt Ut sed Fusce vitae mauris eget Nam lacus suscipit ullamcorper Ut euismod Nunc ornare egestas elit sem Vestibulum est ullamcorper augue', 9, '2015-06-03', 528, 'blandit vel dolor arcu eget Ut'),
	(67, 2, 'tempus viverra Nulla orci facilisis', 'mattis fringilla sem fringilla metus ac lorem at facilisis id velit eget nisl vitae volutpat nec semper Cras a commodo ut', 'tristique quis amet Donec id est cursus Nulla vitae Pellentesque fringilla amet dictum imperdiet ultricies nec faucibus Aenean nec arcu Aenean suscipit odio Maecenas id ligula sit turpis porta in sit et ac Mauris venenatis sed quam Nunc Etiam Mauris nibh dolor in mauris at et rhoncus turpis vitae Nulla rhoncus', 8, '2016-01-22', 788, 'feugiat dictum eros'),
	(68, 1, 'risus quis risus ut eget non erat sodales porta sit', 'Integer Duis id condimentum bibendum vitae Curabitur amet Maecenas tempor non vitae molestie fermentum ipsum tortor vitae ut', 'ultricies eu libero ante accumsan ante ut lectus eu lobortis sit nec tellus bibendum sed at egestas tempor Sed a adipiscing hendrerit placerat elit fermentum nec quis euismod massa iaculis Praesent eget vel ut porta tincidunt dignissim Praesent a mauris nec imperdiet tincidunt facilisis est mollis quam Nam ipsum vel egestas elementum viverra dui vitae Vestibulum', 9, '2015-07-29', 2845, 'bibendum eu amet'),
	(69, 2, 'non vel malesuada est', 'Nam condimentum ac est suscipit iaculis justo est lacinia velit accumsan et a lorem id', 'purus odio adipiscing fermentum Pellentesque nec eros tincidunt neque Pellentesque mauris blandit porta Donec semper consequat sollicitudin vulputate odio Suspendisse lacus mauris et sit metus vulputate sed amet eget augue ullamcorper orci vestibulum dui imperdiet Integer est at varius iaculis lacus vel eu Pellentesque sodales massa dui suscipit Mauris id laoreet felis in lectus tristique eu quam Sed porta Mauris ut ornare Aenean ac eget', 16, '2014-07-24', 1798, 'mauris cursus laoreet Fusce ut magna'),
	(70, 7, 'Fusce fermentum sit erat magna fermentum commodo tincidunt', 'Vivamus enim eros vitae in adipiscing dolor nec Maecenas vel sollicitudin Quisque iaculis malesuada lacus ipsum dui ligula ipsum scelerisque ut pretium mauris pharetra Donec Aenean tempor mattis nec in posuere', 'metus at Vestibulum in in nisi laoreet id sit tincidunt quis lorem sem hendrerit suscipit Pellentesque neque sed a Integer augue commodo sem non fermentum lectus ac dolor et dui Integer viverra eget non dolor non eget fermentum gravida amet Aenean lacus sem pulvinar elit laoreet sapien Cras consequat porta pellentesque arcu Suspendisse mollis adipiscing Suspendisse magna nisi velit blandit vel facilisis blandit et nec metus consequat massa sit nibh lobortis Nam ligula Donec nisl dignissim eget at turpis Aenean Ut ut ante lorem Ut Curabitur id dui euismod pulvinar', 16, '2016-08-09', 582, 'congue tempor sed interdum'),
	(71, 3, 'id lectus facilisis Pellentesque lacinia molestie ultrices eget', 'nibh dignissim tempor vestibulum tellus amet dui commodo mattis urna est tincidunt tortor neque fringilla quis eget malesuada', 'ut pretium vehicula eu nec Ut vitae nisl Maecenas ante Etiam suscipit ante hendrerit eros massa a malesuada enim ipsum mattis lorem tellus Pellentesque pharetra luctus facilisis hendrerit ultricies est Sed interdum vehicula sem felis dolor quis lorem ac tempus vulputate enim at ultrices vehicula amet consectetur Duis nulla iaculis Ut semper eu bibendum blandit in semper nunc Vivamus sem sagittis libero Donec nec Suspendisse ultricies non purus', 3, '2016-04-12', 133, 'Mauris ipsum consectetur pulvinar'),
	(72, 6, 'metus faucibus dictum id est', 'Mauris mattis est eget fermentum Aenean Proin dignissim elementum Mauris sollicitudin purus tortor justo tempor venenatis congue In mollis vel erat sollicitudin metus', 'id sem in vel Proin sollicitudin et nibh varius dui porttitor varius sem sed enim justo ante rutrum ut In Praesent elementum Suspendisse euismod nibh et Phasellus tellus at semper purus posuere lacus a lectus sollicitudin enim ante dui sodales pulvinar Proin nibh sollicitudin sem in id in vitae eleifend vulputate egestas porta sapien nisi amet eget at metus at molestie diam eros vel pretium turpis quis sit Sed metus bibendum justo est Praesent', 8, '2016-01-19', 853, 'lorem nec ut'),
	(73, 4, 'dolor ut fringilla condimentum', 'molestie nec congue Pellentesque Donec Sed eget quis et et sollicitudin vel libero elit posuere malesuada ipsum ullamcorper purus', 'quis Praesent vestibulum nisl Pellentesque Integer non Mauris metus blandit hendrerit Nam erat velit eget feugiat amet dapibus euismod sem arcu neque augue in Sed nulla dignissim nibh imperdiet a ac nulla sed a nec Duis neque arcu imperdiet sapien tempor vitae at quis nec tincidunt non tincidunt euismod hendrerit nunc vel sodales suscipit ornare amet enim sem Nullam nulla Nullam eget tellus justo eu porttitor velit Pellentesque justo sem dui molestie quis vulputate volutpat malesuada interdum Aliquam ultricies nisl vehicula a posuere urna at mollis sollicitudin arcu accumsan malesuada metus vel Donec sed eget Fusce dapibus facilisis consectetur', 16, '2015-05-03', 2800, 'diam pulvinar eget'),
	(74, 7, 'ut Nulla nibh nec consectetur et Quisque ipsum Nam sollicitudin', 'dolor pharetra metus turpis mi nisl dapibus purus malesuada ipsum ligula enim tincidunt massa blandit lectus eget odio sit a tempus turpis in nisi', 'quam felis sagittis Proin commodo non Morbi vitae dui laoreet quis placerat a libero sodales vel Etiam Duis elit egestas dui mauris amet sed ac diam metus nec ante cursus quis vitae tincidunt augue Fusce diam nunc ac Curabitur lacus Ut libero Sed a congue a vitae volutpat urna ante egestas nec interdum Phasellus ut vestibulum nec Integer arcu mattis dolor Donec In Aenean pulvinar', 8, '2015-03-14', 1227, 'elementum dapibus in et metus sed'),
	(75, 2, 'Phasellus Cras volutpat at sodales Proin', 'et Fusce a odio rhoncus Nulla in nec ultrices neque purus Aenean Donec dapibus feugiat interdum quis nibh eros lorem nunc mauris aliquet faucibus', 'sit varius facilisis tortor elementum eu placerat nibh porttitor neque et nisl gravida sed orci nunc ullamcorper quis Nam blandit risus scelerisque enim lectus et convallis leo mauris lacus ut sapien a eros laoreet vel laoreet nisi Cras fermentum rutrum sapien in eget nisl iaculis malesuada lorem ipsum Mauris metus', 7, '2014-08-14', 2841, 'arcu ac feugiat tristique tempor'),
	(76, 1, 'Quisque porttitor dolor tellus blandit eros varius eget et', 'imperdiet fringilla mollis nec eu sollicitudin non facilisis lectus nisl Pellentesque vitae vulputate molestie dolor ut at est velit quam leo Nullam magna Aliquam ac vel a', 'gravida id semper placerat massa fermentum placerat malesuada sit gravida eros pretium a augue ut Ut non in consequat sapien convallis sit velit dapibus ut vehicula id quam metus at dolor vel at velit sem vel accumsan lectus In Mauris interdum sem interdum porta pulvinar gravida Vivamus pulvinar ligula tincidunt nibh Vivamus in ornare risus enim egestas', 2, '2014-08-31', 2743, 'eros velit convallis sodales porta'),
	(77, 4, 'mi egestas blandit quam elit Pellentesque amet', 'vel Etiam lobortis Phasellus Donec sed luctus ut nulla venenatis mollis metus enim imperdiet Morbi', 'rhoncus metus mattis a in sagittis nibh eu aliquet mollis velit Sed elit non eget quam Nulla Nullam et fringilla tortor dictum eu nisi amet risus non suscipit Nunc metus Fusce euismod eget tellus eros nec eget Donec ante pretium rhoncus tristique porta tempus egestas tempus vitae a arcu Proin mattis non consectetur at dapibus est Vestibulum sem erat tortor hendrerit lectus hendrerit Proin libero convallis velit aliquam suscipit a at ut Quisque Nullam sed a sed ante viverra sed suscipit auctor tempus placerat metus imperdiet sem imperdiet amet quis venenatis mollis quam nec', 18, '2016-12-10', 1283, 'metus purus porta ipsum Duis'),
	(78, 2, 'condimentum sem a lectus imperdiet nec quis', 'In eu tincidunt Aliquam nulla sed sed lobortis iaculis aliquam pellentesque tortor consectetur rhoncus amet Donec condimentum sed dui vulputate pharetra in auctor in erat varius fermentum at egestas dolor quis id eget est congue', 'at in ac sed lobortis tempus facilisis venenatis facilisis auctor sit risus diam dapibus nibh mattis consectetur iaculis Pellentesque elit ornare egestas Nam feugiat Nulla ultricies imperdiet sit nec elementum Ut Donec commodo vehicula in gravida augue eget ac posuere massa nec iaculis ac sed risus a Vivamus quis Nunc et metus enim ultrices risus commodo metus tellus velit a volutpat Pellentesque purus mattis scelerisque justo scelerisque pulvinar lorem adipiscing quis malesuada eget pretium at sagittis lorem eros In sollicitudin Curabitur libero sed tortor pretium et in mi a ut placerat eget Phasellus gravida non sed nunc lacinia non mattis', 15, '2014-09-08', 740, 'urna et sodales libero a nec'),
	(79, 5, 'tempor tortor Aenean leo', 'odio semper cursus eget pulvinar sit lectus felis lacinia ultricies eget sodales sed eget in amet porta at mauris nunc feugiat accumsan odio elementum ac', 'ornare ultrices gravida Phasellus nulla Curabitur a mi Donec vel In commodo Sed congue nunc lorem libero Quisque sit nisl purus Nunc tempor tempus in massa mattis rutrum et eget hendrerit ac libero sodales aliquam mauris eget rhoncus a lectus ac eget est porttitor venenatis tempus erat condimentum Donec at mollis tempor Nunc orci id non odio malesuada at mattis elementum non nisi volutpat Quisque euismod nunc ac est eu magna sed a rhoncus justo velit Donec', 4, '2014-12-30', 1558, 'laoreet ipsum eu Donec'),
	(80, 3, 'lacinia arcu neque erat purus', 'et nisi commodo interdum dui nec Sed ornare facilisis id justo sapien elementum tristique vitae sit metus ligula lobortis enim mauris turpis Pellentesque id sed hendrerit eu sed est fermentum id turpis libero sollicitudin', 'sit placerat eget sed Integer nibh amet ac Nulla Maecenas elit quis quis sodales libero mattis quis adipiscing lectus augue a purus turpis pulvinar rhoncus quis laoreet a rutrum mauris porta consectetur eget nisl viverra vitae condimentum adipiscing sodales iaculis nisl velit nulla Aliquam eu arcu ut eros feugiat Vivamus vel', 19, '2014-08-04', 342, 'ac lobortis sed'),
	(81, 6, 'augue Praesent ullamcorper nulla sit Vestibulum Duis', 'ipsum varius volutpat nibh quis porttitor ut non sollicitudin urna vitae euismod pulvinar eu rhoncus dapibus posuere dolor nec elit quis varius eros', 'rutrum Integer vestibulum amet at sit dictum lorem mi ut Suspendisse elementum varius Morbi fringilla leo orci tincidunt quam velit iaculis dui sem eget quis hendrerit enim ornare sollicitudin sollicitudin facilisis molestie ut Etiam est odio Donec at gravida nisi iaculis libero Aenean egestas velit quis sed massa Maecenas at Donec elit leo sagittis massa fringilla lectus nec vitae nibh ullamcorper ultrices arcu in sed Phasellus tellus euismod sapien pulvinar nulla in odio mi Fusce ullamcorper leo luctus ligula ipsum eu Phasellus nec Etiam tellus volutpat purus feugiat convallis magna', 8, '2016-06-04', 196, 'justo ultricies sed'),
	(82, 1, 'posuere vel Quisque nunc pharetra vitae eget sollicitudin mollis', 'Morbi lacinia commodo felis cursus arcu gravida nulla porttitor est congue iaculis fringilla ipsum eget sodales semper tellus congue dignissim sodales Nulla velit nec lacus Donec interdum Curabitur', 'felis gravida elit at nibh Etiam ut malesuada mattis tortor a placerat Nulla imperdiet nunc Aenean posuere cursus risus porttitor lacinia sem scelerisque vitae a nunc aliquam ut condimentum Fusce Morbi Vestibulum ipsum tempor sem eget feugiat luctus rutrum Praesent auctor cursus at Cras Donec tincidunt a Pellentesque volutpat velit gravida orci lobortis vestibulum lorem egestas euismod eget suscipit in mollis aliquet nisl sem Integer egestas eu Pellentesque condimentum vehicula lacus non consectetur non vel metus imperdiet Morbi imperdiet bibendum Sed convallis ac malesuada vitae et Nullam hendrerit at a purus condimentum euismod eu Donec aliquet', 2, '2014-06-10', 2827, 'rutrum Vestibulum et a euismod'),
	(83, 7, 'lectus erat dapibus ornare justo porta et dolor', 'aliquet Nam elementum eu tortor luctus at Sed Sed facilisis amet ipsum rhoncus at suscipit blandit in euismod id et eget enim eu ultricies vestibulum sed Maecenas purus ipsum lobortis', 'pretium amet risus laoreet ut dolor laoreet in velit turpis Etiam tellus elit tempor id aliquam vel semper pellentesque sodales velit eleifend feugiat quam non a Duis dignissim magna semper Cras nunc tincidunt Aenean varius sem quis In erat Nunc Cras consequat a Phasellus sagittis odio ligula ultrices mi sem tincidunt a tincidunt et Ut Vivamus purus purus lorem erat ac Vestibulum purus dignissim Nunc dolor nisl vel hendrerit sagittis nec ullamcorper rhoncus blandit Quisque ultrices tempor vitae massa urna id urna mollis pellentesque libero erat sem ultricies arcu vel porta Praesent Mauris ipsum non et eget sagittis', 16, '2015-03-11', 474, 'a dolor Sed id ultrices tempus'),
	(84, 2, 'Vestibulum semper tincidunt Nulla amet feugiat Phasellus ipsum', 'dolor eros Cras in eget tortor cursus leo eu erat urna Pellentesque ipsum lacinia arcu felis', 'pharetra eu Donec blandit suscipit egestas dignissim dignissim turpis aliquam sagittis Mauris est Ut consequat et nisi pretium pulvinar nunc turpis est et sit vitae egestas Curabitur augue vitae Integer mollis metus lectus neque Ut metus euismod lorem congue est mollis Sed augue ornare tortor diam ipsum viverra sit euismod et sed quis bibendum mollis eu at at Nunc', 7, '2017-01-21', 395, 'leo sagittis Pellentesque turpis vel cursus'),
	(85, 3, 'auctor augue dolor ut fringilla', 'interdum Sed placerat egestas nunc ut ut ac nisl tortor molestie enim tortor et malesuada neque ornare lacus arcu amet sed placerat nibh sem eros sagittis', 'varius ullamcorper facilisis facilisis sit pulvinar hendrerit elementum ut et volutpat velit malesuada porta Curabitur porttitor tortor Donec quam purus scelerisque sed tellus tellus augue elementum eget fermentum facilisis justo lectus pharetra lorem Pellentesque tempus dictum Mauris tellus tellus sit mauris sed blandit Nullam Fusce dictum In Curabitur at justo Proin ipsum Phasellus massa pulvinar luctus diam non volutpat interdum odio varius dignissim commodo sagittis tempor aliquet vestibulum sit sit Nunc auctor rutrum interdum ac accumsan faucibus sagittis nec erat iaculis bibendum libero a massa nec', 11, '2016-12-16', 914, 'libero Cras Etiam volutpat'),
	(86, 4, 'pretium sed tristique diam neque molestie pulvinar', 'Phasellus non at amet mattis amet Duis in convallis id ac congue eros a eget mattis iaculis Praesent lacus Aliquam a', 'egestas sed consequat bibendum Curabitur tempor in fermentum malesuada dolor Aliquam nibh mollis elementum vitae metus tortor accumsan ultricies feugiat leo feugiat quis ac tincidunt porta purus quis tincidunt molestie amet convallis malesuada volutpat lorem sed lectus Nunc ut in Fusce condimentum faucibus vitae magna elit sagittis felis ultrices lobortis ligula at eu sollicitudin tortor dolor eros nibh Sed', 5, '2016-08-28', 377, 'egestas orci at'),
	(87, 1, 'vestibulum in Vestibulum euismod sem', 'malesuada in Sed lacinia auctor ut a mauris ultricies turpis facilisis volutpat Cras dolor lectus faucibus', 'amet vitae lorem at nisl blandit lacinia Vivamus rhoncus bibendum commodo varius sed eu at vestibulum ligula vitae id at venenatis Sed sit nec turpis vel Mauris condimentum lacinia non auctor Phasellus varius elementum eu amet metus vitae Integer a suscipit a turpis dignissim leo felis massa nisi sed massa sollicitudin orci id rhoncus Donec in condimentum auctor egestas lacus magna ut tellus Phasellus leo scelerisque at eros nunc gravida a ante Quisque orci blandit tempus purus at fringilla in Donec tincidunt arcu convallis Nullam eget eleifend hendrerit', 18, '2017-01-18', 618, 'lorem odio Nam ultricies Suspendisse vel'),
	(88, 7, 'nec arcu eu dapibus bibendum vitae nisi accumsan', 'felis molestie lacus id diam Nullam est pellentesque mattis molestie sit dapibus pulvinar fermentum eu ut purus sit suscipit aliquam purus diam viverra Duis justo', 'nisl et Vestibulum at varius aliquet dapibus velit amet consequat vestibulum venenatis mollis sit consectetur sodales laoreet auctor neque a Praesent lorem neque leo amet at at lorem Duis amet amet interdum mauris enim dictum adipiscing scelerisque vitae Mauris cursus Mauris elit magna commodo faucibus mauris gravida venenatis euismod iaculis justo quis orci molestie porttitor pharetra sodales quam pharetra cursus suscipit scelerisque ut eu pretium Phasellus interdum lacinia mauris Nunc Donec tincidunt mauris mattis ut', 3, '2017-03-06', 2121, 'auctor sit tincidunt auctor'),
	(89, 3, 'sed at Aliquam leo lacus', 'Proin Nulla a eget massa tortor tincidunt ullamcorper vulputate eu consectetur quis hendrerit Donec vestibulum lorem et urna iaculis faucibus posuere luctus Fusce sagittis sem iaculis sagittis augue eget convallis erat nunc et', 'turpis nulla Quisque Pellentesque molestie vulputate metus eget Mauris euismod Donec faucibus enim justo est in turpis enim Vestibulum diam cursus vitae erat amet non diam Fusce semper ut dictum Vivamus pellentesque Phasellus nunc In semper porttitor sed nibh nunc accumsan sodales quis ac pretium convallis Donec faucibus sed at mi', 14, '2016-07-16', 498, 'adipiscing Nulla convallis et vitae Donec'),
	(90, 5, 'nibh sodales Phasellus ut ac sed risus', 'id commodo sollicitudin a in a mollis vehicula Maecenas arcu dictum dignissim metus consequat nibh varius', 'at sed non blandit cursus consectetur Nulla massa risus odio dui sed in bibendum ut at hendrerit iaculis tortor eu quam libero nec velit mattis amet orci erat volutpat at ac amet urna lorem massa turpis sodales nibh turpis purus facilisis enim mauris in congue ultricies rhoncus sollicitudin urna aliquet porttitor Sed sit Donec lectus Sed eget', 19, '2016-03-16', 1602, 'metus consectetur Proin porta ut'),
	(91, 5, 'Proin fringilla ac eget justo', 'Cras facilisis erat dictum eu mauris sollicitudin enim molestie volutpat massa Morbi eu congue libero condimentum hendrerit Fusce vel blandit at euismod sit accumsan ut eget ullamcorper odio eget eget turpis', 'ultrices ullamcorper nisl at turpis mollis a sem convallis mattis sapien nulla purus semper Fusce sed pulvinar vel vestibulum turpis tellus orci venenatis consequat a ut imperdiet eget Aenean aliquam mattis posuere ultricies ante Maecenas Nullam sit Integer commodo mi pulvinar adipiscing ut egestas non aliquam a Quisque nec eget Nam vel sit semper ut Nam ut libero imperdiet augue rhoncus vitae lobortis lectus ullamcorper sed elementum ut eleifend odio id sem vulputate vestibulum pretium velit augue', 8, '2016-03-12', 2431, 'aliquet at facilisis'),
	(92, 3, 'enim Etiam pulvinar a', 'Nullam rhoncus eget diam et facilisis odio fermentum ultricies rhoncus Aenean dictum sapien a consectetur nec eget lectus massa diam Etiam ac Donec sagittis dui mauris', 'nisl eget ante purus enim metus a Fusce condimentum sapien odio Fusce mauris et Mauris Vestibulum consectetur in eleifend accumsan consequat vitae In scelerisque in Pellentesque leo sed in sed diam in ipsum placerat eu Sed pulvinar pharetra Curabitur quis tempor enim libero venenatis nec sagittis pretium Praesent eget sit dolor sagittis suscipit ornare velit eros sapien Donec', 20, '2015-07-12', 899, 'egestas augue ut arcu imperdiet'),
	(93, 3, 'tempus arcu a nibh quis vitae sed dictum et dolor', 'turpis dui Maecenas et id ante gravida Donec risus Aliquam quis suscipit ante est pulvinar pulvinar nec sit tincidunt diam id tortor nec ligula vulputate erat mauris at neque', 'dolor ac erat mauris ut ut nibh vitae mauris Donec dui Ut fringilla dolor scelerisque bibendum urna sagittis lorem scelerisque purus amet tellus eleifend in sit porta Aenean vitae a nulla lacus accumsan volutpat fringilla purus scelerisque eu sollicitudin massa tortor elit tellus et at purus sollicitudin ligula lorem facilisis tempor tortor felis interdum placerat eget viverra', 13, '2016-11-13', 1972, 'nibh facilisis scelerisque ac in'),
	(94, 3, 'iaculis laoreet luctus a malesuada', 'Quisque urna elit purus consectetur eget Nulla Donec Etiam turpis dolor quam ut ac Nullam magna egestas adipiscing gravida ultrices et cursus nisl facilisis dictum', 'diam quam libero justo Morbi id consectetur Cras sed porttitor commodo porta dolor turpis non purus ut vulputate et massa urna faucibus condimentum sollicitudin aliquam sit turpis ultricies Morbi vel facilisis ultricies eros purus orci laoreet at fringilla Curabitur vitae Nulla placerat Aliquam Nulla ligula In magna sapien eget eget elit ante dignissim elit', 6, '2016-01-17', 2900, 'Suspendisse mollis nisi rhoncus cursus'),
	(95, 6, 'elementum dapibus lectus vitae malesuada ante', 'nibh Nulla elementum tortor feugiat eros felis Suspendisse iaculis rhoncus et sollicitudin posuere velit est quam ante et lobortis magna bibendum mi euismod Donec vel vitae', 'ligula lorem non vel tincidunt ac lacus accumsan et et sit ac Donec ultricies pretium scelerisque mauris purus lectus eleifend Suspendisse lectus nulla eu sagittis commodo quam dignissim nunc a luctus non vehicula enim rhoncus libero quis at amet arcu risus Etiam Phasellus dignissim nibh in tincidunt malesuada congue risus Nullam', 17, '2017-02-04', 2498, 'libero lacus quam eu semper felis'),
	(96, 5, 'auctor vehicula vulputate lacinia', 'lectus urna volutpat vulputate dapibus sit velit justo est auctor Mauris eget a quis tellus vestibulum luctus ut Nunc porta volutpat vel laoreet vitae volutpat vulputate elit fringilla nisi ac sollicitudin In id hendrerit sit', 'Integer suscipit Suspendisse vel sed Integer vel euismod ante facilisis massa sed lorem nisl sem felis scelerisque dui nisl quis iaculis Pellentesque elit nunc diam vulputate in Vestibulum eu auctor a Sed a at posuere sed eget Donec leo et facilisis ac est ligula tempus libero eget Phasellus nunc laoreet imperdiet Praesent Nulla erat elit leo pretium gravida lacus ac sollicitudin mauris purus Mauris', 12, '2016-11-13', 2781, 'quis mi mauris quam'),
	(97, 7, 'Nullam lectus lacus Nulla', 'Curabitur mauris sed eget velit consectetur velit Vivamus eleifend felis mauris metus ac Etiam consequat vestibulum a quam elit pretium', 'vitae turpis libero mi ut nisi et eget ipsum mattis Vivamus dignissim varius Fusce tempor congue eleifend rhoncus volutpat et Vivamus nisi eu faucibus Sed at et turpis scelerisque adipiscing lobortis sed elementum Vivamus ut rhoncus ultricies Sed cursus suscipit commodo Vivamus lorem euismod sit in sapien turpis sed massa dapibus eu sodales arcu dolor Nulla libero erat nulla nulla lacus Phasellus lacus dictum pharetra augue libero Vivamus tristique lectus Cras consequat a Mauris volutpat metus vestibulum cursus nibh Proin sagittis facilisis dignissim', 16, '2016-10-01', 990, 'a In lacinia velit tortor Nunc'),
	(98, 1, 'Etiam Nullam augue ligula quis cursus sed egestas', 'molestie interdum adipiscing Sed lobortis tristique congue ut nibh Nulla rutrum eu quis quam accumsan vel sit leo tellus malesuada Curabitur at non magna magna eget porta', 'semper metus eget magna rutrum euismod ipsum Pellentesque suscipit commodo gravida Ut diam ultricies molestie ut consequat ante nunc velit sed aliquet a vitae pharetra at ante rutrum erat vehicula posuere egestas libero bibendum at augue quis volutpat facilisis ligula sed ultricies dui porta eu sit sed eu sed Sed non vehicula ut Donec condimentum erat malesuada ac molestie mauris Phasellus quam amet sit ut Suspendisse diam posuere pulvinar Quisque Integer felis tempor diam semper at at at non porta scelerisque nulla rhoncus nisl volutpat nunc neque Aliquam Phasellus facilisis Fusce convallis ac nisi Praesent metus', 13, '2016-04-29', 1854, 'porta Quisque turpis Praesent'),
	(99, 4, 'congue placerat arcu turpis ut Sed', 'metus id Phasellus lobortis laoreet tellus eget Proin blandit Donec ultricies a facilisis enim ipsum leo faucibus Ut commodo semper eros', 'id ultrices molestie laoreet Curabitur lacus porta in Vivamus sit imperdiet imperdiet eget lorem sit dignissim elit ullamcorper viverra bibendum Morbi velit libero feugiat egestas turpis risus quis at sem id fringilla velit molestie molestie tincidunt eget arcu venenatis nulla enim sit Sed placerat ullamcorper interdum lorem quis eu non eu felis porta Aliquam interdum eros id id et dolor et Etiam Praesent Cras pulvinar sit congue Proin leo sed amet Phasellus turpis pretium odio Donec non laoreet id adipiscing pretium luctus turpis Duis Duis sed', 5, '2016-04-03', 2889, 'tincidunt luctus lobortis lectus'),
	(100, 7, 'vel velit Cras risus', 'venenatis condimentum auctor lectus a facilisis a sit ipsum feugiat dignissim vitae nisi vel feugiat eleifend ipsum', 'nec ac tincidunt Curabitur iaculis lacinia amet eget a non elit convallis amet odio pharetra tempus tortor amet commodo non sodales in euismod varius eget sagittis turpis mauris vehicula enim libero ut leo imperdiet tempus id quam lacinia mi Ut odio a sem tincidunt ornare tortor egestas egestas sapien sit Ut nisi est tempor rhoncus at in porta velit auctor nibh', 12, '2014-05-18', 1081, 'dui In lorem nunc orci');
/*!40000 ALTER TABLE `yazilar` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
